# Generated by Django 4.2 on 2023-04-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create',
            new_name='created',
        ),
    ]
